CREATE TABLE users(
	username VARCHAR(20) NOT NULL PRIMARY KEY,
	fullname VARCHAR(40) NOT NULL,
	email VARCHAR(40) NOT NULL,
	password VARCHAR(256) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);